### ISSUE TITLE
Issues with conversion of passed array to `color` in `add_plot`

### ISSUE THREAD

**Issue by beddalumia** [jacobwilliams/pyplot-fortran#37]
So far I've had a _great_ time with this package, as much as it becoming the main plotting backend of my new project [HoneyTools](https://github.com/QcmPlab/HoneyTools). Now I wanted to switch away from the default matplotlib colors, so to have a plotting-style that is coherent with the logo and the general look of the project, but I encounter some tricky problems in doing that.

--------

I define these two colors:

```fortran
real(8), parameter :: F(3) = [0.4510d0, 0.3098d0, 0.5882d0] ! Fortran-lang color 
real(8), parameter :: Y(3) = [0.9608d0, 0.8157d0, 0.0118d0] ! HoneyTools' Yellow
```

And call `add_plot` as

```fortran
! Sublattice "A"
call plt%add_plot(Ax,Ay,label='',linestyle='o',markersize=5,color=F)
! Sublattice "B"
call plt%add_plot(Bx,By,label='',linestyle='o',markersize=5,color=Y)
```

But I get the following runtime errors:

```python
Traceback (most recent call last):
  File "/Users/gbellomia/Dropbox/SISSA/QcmPlab/HoneyTools/xy_plot.py", line 1648, in <module>
    ax.plot(x,y,"o",linewidth=3,markersize=5,label="",color=(0.49999999999999928,-1.0000000000000000,7.7942286340599480))
  File "/usr/local/lib/python3.10/site-packages/matplotlib/axes/_axes.py", line 1635, in plot
    lines = [*self._get_lines(*args, data=data, **kwargs)]
  File "/usr/local/lib/python3.10/site-packages/matplotlib/axes/_base.py", line 312, in __call__
    yield from self._plot_args(this, kwargs)
  File "/usr/local/lib/python3.10/site-packages/matplotlib/axes/_base.py", line 538, in _plot_args
    return [l[0] for l in result]
  File "/usr/local/lib/python3.10/site-packages/matplotlib/axes/_base.py", line 538, in <listcomp>
    return [l[0] for l in result]
  File "/usr/local/lib/python3.10/site-packages/matplotlib/axes/_base.py", line 531, in <genexpr>
    result = (make_artist(x[:, j % ncx], y[:, j % ncy], kw,
  File "/usr/local/lib/python3.10/site-packages/matplotlib/axes/_base.py", line 351, in _makeline
    seg = mlines.Line2D(x, y, **kw)
  File "/usr/local/lib/python3.10/site-packages/matplotlib/lines.py", line 370, in __init__
    self.set_color(color)
  File "/usr/local/lib/python3.10/site-packages/matplotlib/lines.py", line 1030, in set_color
    mcolors._check_color_like(color=color)
  File "/usr/local/lib/python3.10/site-packages/matplotlib/colors.py", line 130, in _check_color_like
    raise ValueError(f"{v!r} is not a valid value for {k}")
ValueError: (0.4999999999999993, -1.0, 7.794228634059948) is not a valid value for color
```

```python
Traceback (most recent call last):
  File "/Users/gbellomia/Dropbox/SISSA/QcmPlab/HoneyTools/xy_plot.py", line 2248, in <module>
    ax.plot(x,y,"o",linewidth=3,markersize=5,label="",color=(0.49999999999999928,-1.0000000000000000,9.5262794416288248))
  File "/usr/local/lib/python3.10/site-packages/matplotlib/axes/_axes.py", line 1635, in plot
    lines = [*self._get_lines(*args, data=data, **kwargs)]
  File "/usr/local/lib/python3.10/site-packages/matplotlib/axes/_base.py", line 312, in __call__
    yield from self._plot_args(this, kwargs)
  File "/usr/local/lib/python3.10/site-packages/matplotlib/axes/_base.py", line 538, in _plot_args
    return [l[0] for l in result]
  File "/usr/local/lib/python3.10/site-packages/matplotlib/axes/_base.py", line 538, in <listcomp>
    return [l[0] for l in result]
  File "/usr/local/lib/python3.10/site-packages/matplotlib/axes/_base.py", line 531, in <genexpr>
    result = (make_artist(x[:, j % ncx], y[:, j % ncy], kw,
  File "/usr/local/lib/python3.10/site-packages/matplotlib/axes/_base.py", line 351, in _makeline
    seg = mlines.Line2D(x, y, **kw)
  File "/usr/local/lib/python3.10/site-packages/matplotlib/lines.py", line 370, in __init__
    self.set_color(color)
  File "/usr/local/lib/python3.10/site-packages/matplotlib/lines.py", line 1030, in set_color
    mcolors._check_color_like(color=color)
  File "/usr/local/lib/python3.10/site-packages/matplotlib/colors.py", line 130, in _check_color_like
    raise ValueError(f"{v!r} is not a valid value for {k}")
ValueError: (0.4999999999999993, -1.0, 9.526279441628825) is not a valid value for color
```

Which imo highlight a clear problem in real array to string conversion, as requested here:

https://github.com/jacobwilliams/pyplot-fortran/blob/da68b01a911353292e260d1733c67b08599ad941/src/pyplot_module.F90#L375-L380

---------

An additional peculiar thing that I found is that the reported _python_ runtime behavior happens if the `-Wall` flag is passed to fpm. Without it I get an obscure _fortran_ runtime error:

```
At line 377 of file build/dependencies/pyplot-fortran/src/pyplot_module.F90
Fortran runtime error: Index '3' of dimension 1 of array 'color' outside of expected range (2:1)
```

How is the expected range (2:1) if I pass a dimension(3) array? Why does `-Wall` make me bypass the problem in Fortran (?! this really surprises me...) and get to the python exception? All this is quite strange to me and I have no idea of what could be happening, so I report it here, for documentation purposes.

> Note: I saw that the `color=[a,b,c]` option in `add_plot` is currently not included in the CI test-suite. So this may be a long living problem here.

**Comment by jacobwilliams** [comment]
I think you need to show me a full compilable version of the code that produces these errors. You've got something else wrong that I'm not seeing here. Maybe some uninitialized variables or something like that. 

If I construct the following example based on the information I do have, I don't see these problems:

```fortran
    program color_test

    use pyplot_module, only : pyplot, wp => pyplot_wp

    implicit none
    
    type(pyplot) :: plt   !! pytplot handler
    integer :: istat
    real(wp), parameter :: F(3) = [0.4510d0, 0.3098d0, 0.5882d0] ! Fortran-lang color 
    real(wp), parameter :: Y(3) = [0.9608d0, 0.8157d0, 0.0118d0] ! Yellow
 
    real(wp),dimension(3),parameter :: Ax = [1,2,3]
    real(wp),dimension(3),parameter :: Ay = [1,2,3]
    real(wp),dimension(3),parameter :: Bx = [1,2,3]
    real(wp),dimension(3),parameter :: By = [4,5,6]

    call plt%initialize(figsize=[20,10],title='color test')

    call plt%add_plot(Ax,Ay,label='',linestyle='o',markersize=5,color=F)
    call plt%add_plot(Bx,By,label='',linestyle='o',markersize=5,color=Y)

    call plt%savefig('color_test.png', pyfile='color_test.py',istat=istat)

    end program color_test
```

**Comment by beddalumia** [comment]
You're right, your minimal test case works properly in my project too! There has to be something subtle indeed. I'll now proceed to carefully bend your program towards my actual use case until it breaks, and then we can discuss. Thanks for the prompt!

**Comment by beddalumia** [comment]
Ok, this is embarrassing: I just had a _local_ y variable somewhere in the middle, shadowing the module-wide parameter Y. Sorry for bothering you for such a naive error on my part and thanks for your time!
